[package]
name = "mpd-notify-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#notify = "5.1.0"
notify-rust = "4"
mpd = "0.0.12"
toml = "0.7.2"
serde = "1.0.152"
